title: "作って学ぶOSの仕組み　学習メモ"
summary: "オペレーティングシステムの仕組みを実際に作りながら学ぶための学習メモです。"
topics: ["OS", "システムプログラミング", "低レイヤー"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - ch-one
  - ch-two
